version: '3.7'

services:
  fabricdns:
    image: busybox
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      - COLUMNS=500
      - GODEBUG=netdns=go
    extra_hosts:
      - "orderer1.example.com:172.21.192.255"
      - "orderer2.example.com:172.21.192.255"
      - "orderer3.example.com:172.21.192.255"
      - "peer0.org1.example.com:172.21.192.255"
      - "peer0.org2.example.com:172.21.192.255"
      - "peer0.org3.example.com:172.21.192.255"
      - "peer0.org4.example.com:172.21.192.255"
      - "peer0.org5.example.com:172.21.192.255"
      - "peer0.org6.example.com:172.21.192.255"
      - "peer0.org7.example.com:172.21.192.255"
      - "peer0.org8.example.com:172.21.192.255"
      - "peer0.org9.example.com:172.21.192.255"
